### ISSUE TITLE
Use Checks API to highlight lines in PR Diff View

### ISSUE THREAD

**Issue by warrenbuckley** [gaurav-nelson/github-action-vale-lint#4]
Hello
This GitHub action is great, but I think it would be neat to add the error messages directly inline to the diff view of PRs, which can be done with the GitHub Checks API
https://developer.github.com/v3/checks/runs/

Is this something that you would consider adding or improving?

For example here is a GitHub Action that uses the checks API to highlight which lines have issues
https://github.com/gimenete/eslint-action

I know the vale tool has an `--output=JSON` flag that you could consider using and looping over to create annotations on a checks API. That lists out line numbers, messgae and start and ending characfters that could be mapped over to an `annotations` object
https://developer.github.com/v3/checks/runs/#annotations-object

**Comment by gaurav-nelson** [comment]
Thanks @warrenbuckley I think this makes sense. Thank you for sharing similar projects using the mentioned functionality. I'll try this one. I am not sure when I can get back on this but, I'll update when I can.

**Comment by gaurav-nelson** [comment]
Thank you, I am closing this one as we now have an official Vale action available at https://github.com/errata-ai/vale-action and it handles this feature. I think I'll contribute to that repository and stop creating additional features here.
